export const GOOGLE_FONTS = [
    "Roboto",
    "Open Sans",
    "Montserrat",
    "Lato",
    "Poppins",
    "Source Sans 3",
    "Roboto Condensed",
    "Oswald",
    "Inter",
    "Raleway",
    "Nunito",
    "Ubuntu",
    "Roboto Mono",
    "Playfair Display",
    "Rubik",
    "Lora",
    "PT Sans",
    "Work Sans",
    "Noto Sans",
    "Merriweather",
    "Kanit",
    "Fira Sans",
    "Quicksand",
    "Barlow",
    "Mulish",
    "Titillium Web",
    "Inconsolata",
    "IBM Plex Sans",
    "Heebo",
    "Libre Franklin",
    "DM Sans",
    "Nanum Gothic",
    "Bitter",
    "PT Serif",
    "Mukta",
    "Josefin Sans",
    "Arimo",
    "Dosis",
    "Anton",
    "Oxygen",
    "Cabin",
    "Lobster",
    "Fjalla One",
    "Hind",
    "Pacifico",
    "Bebas Neue",
    "Abel",
    "Crimson Text",
    "Maven Pro",
    "Varela Round",
    "Dancing Script",
    "Exo 2",
    "Signika",
    "Archivo",
    "Bree Serif",
    "Fredoka One",
    "Righteous",
    "Questrial",
    "Abril Fatface",
    "Permanent Marker",
    "Cinzel",
    "Comfortaa",
    "Teko",
    "Shadows Into Light",
    "Asap",
    "Rokkitt",
    "Vollkorn",
    "Acme",
    "Francois One",
    "Prompt",
    "Catamaran",
    "Cairo",
    "Crete Round",
    "Patua One",
    "Alegreya",
    "Overpass",
    "Changa",
    "Cormorant Garamond",
    "Courgette",
    "Luckiest Guy",
    "Karla"
] as const;
